# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: John Benson
email: john@john-benson.com
description: AI, Digital Forensics and Photography 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://john-benson.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jur1st
github_username:  jur1st


# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
sass:
  sass_dir: _sass
  style: compressed

paginate: 5 # amount of posts to show
paginate_path: /page:num/

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections:
  ai:
    output: true
    permalink: /ai/:path/



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      classes: wide
      previous_next_links: false

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      previous_next_links: false

  # _ai (including all subfolders)
  - scope:
      path: "_ai"
    values:
      layout: single
      author_profile: true
      classes: wide
      previous_next_links: false

  # Specific _ai subfolders (if needed)
  - scope:
      path: "_ai/case-studies"
    values:
      layout: single
      author_profile: true
      classes: wide
      previous_next_links: false

  - scope:
      path: "_ai/prompts"
    values:
      layout: single
      author_profile: true
      classes: wide
      previous_next_links: false



include:
  - _ai