# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: John Benson
email: john@john-benson.com 
description: >- # this means to ignore newlines until "baseurl:"
  John Benson is an attorney working in e-discovery and digital forensics in Kansas City. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnbensondotcom.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: john_benson
github_username:  jur1st

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
# Other Options
excerpt_separator: <!--more-->
show_excerpts: true
kramdown:
      footnote_backlink: "&#8617;&#xfe0e;"

# Pagination Options
paginate: 5
paginate_path: "/page-:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
